"""Independent oracle corrections; original experiment bytes remain immutable."""
import copy
import importlib.util
import json
from pathlib import Path
import unittest

ROOT = Path(__file__).resolve().parents[1]
spec = importlib.util.spec_from_file_location("product_oracle", ROOT / "oracle/oracle.py")
oracle = importlib.util.module_from_spec(spec)
spec.loader.exec_module(oracle)


class OracleRevisionTests(unittest.TestCase):
    def test_contradictory_profile_cannot_be_rebound_to_acceptance(self):
        folder=ROOT/'tests/fixtures/oracle-revision'
        candidate=(folder/'candidate.capyrc').read_bytes();profile=(folder/'profile.capya').read_bytes()
        doc=json.loads((folder/'document.json').read_bytes());release=json.loads((folder/'release.json').read_bytes())
        parts=oracle.unpack(profile);p=json.loads(parts['ACCEPTANCE-PROFILE.json'])
        p['interaction_expectations']['purpose']='A different exact purpose.'
        parts['ACCEPTANCE-PROFILE.json']=oracle.canon(p);profile=oracle.pack(parts)
        doc['identity']['profile_bundle_sha256']=oracle.sha(profile)
        doc['identity_sha256']=oracle.sha(oracle.canon(doc['identity']));doc['acceptance_id']='acc_'+doc['identity_sha256'][:32]
        with self.assertRaisesRegex(ValueError,'interaction_pairing'):
            oracle.validate(candidate,profile,oracle.canon(doc),release)

    def test_omitted_unsafe_artifact_can_have_equal_portable_projections(self):
        folder=ROOT/'tests/fixtures/oracle-revision'
        candidate=(folder/'candidate.capyrc').read_bytes();profile=(folder/'profile.capya').read_bytes()
        doc=json.loads((folder/'document.json').read_bytes());release=json.loads((folder/'release.json').read_bytes())
        doc.update(schema='capy.independent-application-rejection/v0',status='REJECTED',classification='REJECTED_ARTIFACT_SET_MISMATCH')
        doc['cases'][0].update(matched=False,classification='REJECTED_ARTIFACT_SET_MISMATCH')
        self.assertTrue(oracle.validate(candidate,profile,oracle.canon(doc),release))
    def test_source_names_and_strict_artifact_names(self):
        for name in (".gitignore", "_helpers.py", "pkg/__init__.py", "pkg/.data"):
            oracle.safe_source(name)
        for name in ("../x", "/absolute", "a\\b", "a/./b", "a//b", ".git/config", "A/.GIT/HEAD", "CON.txt", "name.", "x:y", "bad\x00name"):
            with self.subTest(name=name), self.assertRaises(ValueError):
                oracle.safe_source(name)
        for name in (".gitignore", "_artifact.txt"):
            with self.assertRaises(ValueError):
                oracle.safe(name)

    def test_original_file_hashes_unchanged(self):
        folder = ROOT / "campaigns/independent_application_acceptance_v0/oracle-original"
        frozen = json.loads((folder / "FREEZE.json").read_bytes())
        for name, digest in frozen["files"].items():
            self.assertEqual(oracle.sha((folder / name).read_bytes()), digest, name)

    def test_receipt_numeric_aliases_rejected(self):
        # Original independently scored copied document, not generated by product code.
        folder = ROOT / "tests/fixtures/oracle-revision"
        candidate = (folder / "candidate.capyrc").read_bytes()
        profile = (folder / "profile.capya").read_bytes()
        document = (folder / "document.json").read_bytes()
        release = json.loads((folder / "release.json").read_bytes())
        self.assertTrue(oracle.validate(candidate, profile, document, release))
        original = json.loads(document)
        mutations = [lambda d: d["cases"][0]["expected"]["artifacts"][0].update(size_bytes=19.0),
                     lambda d: d["toolchain"]["authoring_bundle"].update(size_bytes=31836.0)]
        for mutate in mutations:
            doc = copy.deepcopy(original); mutate(doc)
            with self.assertRaises(ValueError):
                oracle.validate(candidate, profile, oracle.canon(doc), release)
